In [2]:
import numpy as np
a = np.random.randn(5)
print(a)

[-0.35035372 -0.39629845 -0.73466674  0.2591841  -0.40945728]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.44263952  1.12456271 -0.89942883  1.23716131  1.39043497]


In [5]:
print(np.dot(a, a.T))

5.733420740238904


In [6]:
a=np.array([[2,1],[1,3]])
print(a)

[[2 1]
 [1 3]]


In [7]:
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]


In [4]:
#+begin_src python

x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
print(y.shape)

#+end_src

(1, 2)
